/** Canonical maritime ranks — same order as RANK_PRECEDENCE in app/rank_normalization.py */
export const CANONICAL_POSITION_OPTIONS = [
  "Master",
  "Chief Engineer",
  "Chief Officer",
  "Chief Officer Trainee",
  "Second Engineer",
  "Second Engineer Trainee",
  "Second Officer",
  "Third Engineer",
  "Third Officer",
  "Fourth Engineer",
  "Electro Technical Officer",
  "Gas Engineer",
  "Junior Officer",
  "Deck Cadet",
  "Engine Cadet",
  "Electrician",
  "Boatswain",
  "Pumpman",
  "Able Seaman",
  "Ordinary Seaman",
  "Cook",
  "Motorman",
  "Oiler",
  "Wiper",
  "Fitter",
];
