from __future__ import annotations

import os
import smtplib
from dataclasses import dataclass
from datetime import date, timedelta
from email.mime.text import MIMEText
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from models.db import SessionLocal, init_db
from models.schema import Candidate, Certificate, Document

WARNING_DAYS = 240  # ~8 months


@dataclass
class ExpiryItem:
    candidate_id: int
    candidate_name: str
    item_type: str
    item_name: str
    expiry_date: date
    days_left: int


def _candidate_name(candidate: Candidate) -> str:
    full_name = (candidate.full_name or "").strip()
    if full_name:
        return full_name
    parts = [candidate.surname or "", candidate.first_name or "", candidate.middle_name or ""]
    return " ".join(part for part in parts if part).strip() or f"Candidate #{candidate.candidate_id}"


def _collect_expiry_items() -> list[ExpiryItem]:
    session = SessionLocal()
    try:
        today = date.today()
        limit = today + timedelta(days=WARNING_DAYS)
        results: list[ExpiryItem] = []

        docs = (
            session.query(Document, Candidate)
            .join(Candidate, Candidate.candidate_id == Document.candidate_id)
            .filter(Document.date_of_expiry.is_not(None))
            .filter(Document.date_of_expiry <= limit)
            .all()
        )
        for doc, candidate in docs:
            if doc.date_of_expiry is None:
                continue
            days_left = (doc.date_of_expiry - today).days
            results.append(
                ExpiryItem(
                    candidate_id=candidate.candidate_id,
                    candidate_name=_candidate_name(candidate),
                    item_type="document",
                    item_name=doc.document_type or "Unknown document",
                    expiry_date=doc.date_of_expiry,
                    days_left=days_left,
                )
            )

        certs = (
            session.query(Certificate, Candidate)
            .join(Candidate, Candidate.candidate_id == Certificate.candidate_id)
            .filter(Certificate.expiry_date.is_not(None))
            .filter(Certificate.expiry_date <= limit)
            .all()
        )
        for cert, candidate in certs:
            if cert.expiry_date is None:
                continue
            days_left = (cert.expiry_date - today).days
            results.append(
                ExpiryItem(
                    candidate_id=candidate.candidate_id,
                    candidate_name=_candidate_name(candidate),
                    item_type="certificate",
                    item_name=cert.certificate_type or "Unknown certificate",
                    expiry_date=cert.expiry_date,
                    days_left=days_left,
                )
            )

        return sorted(results, key=lambda item: item.days_left)
    finally:
        session.close()


def _build_email_body(items: list[ExpiryItem]) -> str:
    if not items:
        return "No documents or certificates expiring within the next 8 months."

    lines = [
        "Expiry warning report",
        "",
        f"Items expiring in <= {WARNING_DAYS} days:",
        "",
    ]
    for item in items:
        status = "EXPIRED" if item.days_left < 0 else f"{item.days_left} days left"
        lines.append(
            f"- Candidate #{item.candidate_id} ({item.candidate_name}) | "
            f"{item.item_type}: {item.item_name} | "
            f"expiry: {item.expiry_date.isoformat()} | {status}"
        )
    lines.append("")
    lines.append("Generated by scripts/check_expiry.py")
    return "\n".join(lines)


def _send_email(subject: str, body: str) -> None:
    recipients_raw = os.getenv("MANAGER_EMAILS", "")
    recipients = [email.strip() for email in recipients_raw.split(",") if email.strip()]
    if not recipients:
        print("MANAGER_EMAILS is empty; skip email sending.")
        print(body)
        return

    smtp_host = os.getenv("SMTP_HOST", "")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")
    smtp_from = os.getenv("SMTP_FROM", smtp_user or "no-reply@example.com")

    if not smtp_host:
        print("SMTP_HOST not configured; skip email sending.")
        print(body)
        return

    msg = MIMEText(body, _charset="utf-8")
    msg["Subject"] = subject
    msg["From"] = smtp_from
    msg["To"] = ", ".join(recipients)

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        if smtp_user and smtp_password:
            server.login(smtp_user, smtp_password)
        server.sendmail(smtp_from, recipients, msg.as_string())
    print(f"Sent expiry notification to: {', '.join(recipients)}")


def run_expiry_check() -> int:
    init_db()
    items = _collect_expiry_items()
    subject = f"[Maritime CRM] Expiry alert: {len(items)} item(s)"
    body = _build_email_body(items)
    _send_email(subject, body)
    print(f"Processed expiry check: {len(items)} item(s) within {WARNING_DAYS} days.")
    return len(items)


if __name__ == "__main__":
    run_expiry_check()
